name: get_image_cache_network
description: Get image from the cache if exist or from network. In case of error show your placeholder, this package use Dio and Hive.
version: 0.0.3
homepage: https://github.com/alcampospalacios/get_image_cache_network

environment:
  sdk: '>=2.17.3 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  # To handling failures or success cases
  dartz: ^0.10.1
  # To handling request
  dio: ^4.0.6
  # To save in databse
  hive: ^2.2.3
  dio_cache_interceptor: ^3.3.0
  dio_cache_interceptor_hive_store: ^3.2.0
  # provider
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
